tests/lib/rules/type-annotation-spacing.js

Fixes one of the tests related to rule 'type-annotation-spacing'

Fix: incorrect type-annotation-spacing test

---

package.json

Bumping typescript-eslint-parser version from 0.4.0 to 1.0.0

Upgrade: Update typescript-eslint-parser version from 0.4.0 to 1.0.0

---

README.md
docs/rules/no-namespace.md
lib/rules/no-namespace.js
tests/lib/rules/no-namespace.js

This includes
New rule no-namespace

New: Add rule no-namespace

---

README.md
docs/rules/prefer-namespace-keyword.md
lib/rules/prefer-namespace-keyword.js
tests/lib/rules/prefer-namespace-keyword.js

This includes
New rule prefer-namespace-keyword

New: Add rule prefer-namespace-keyword

---

.editorconfig

Chore: Add .editorconfig to project

---

lib/rules/member-ordering.js
tests/lib/rules/member-ordering.js

Fixes an issue where bound methods were processed as properties in classes, interfaces and type literals.

Fix: fixes bound methods ordering (fixes #45)

---

README.md
docs/rules/member-delimiter-style.md
lib/rules/member-delimiter-style.js
tests/lib/rules/member-delimiter-style.js

This includes
New rule member-delimiter-style

New: Add member-delimiter-style (fixes #17)

---

lib/rules/no-explicit-any.js
package.json

Bumps the parser and other deps and fixes errors in no-explicit-any. Closes #54

Chore: Bump deps and fix errors in no-explicit-any

---

package.json

Adds husky precommit hook to validate tests and lint code before committing.

Chore: Add husky precommit hook (fixes #51)

---

lib/rules/no-namespace.js
lib/rules/prefer-namespace-keyword.js
package.json

I have also fixed the prettier config in lint-staged, it did not match the prettier-eslint config

Update: Migrate to typescript-eslint-parser 7.0.0

---

lib/rules/no-unused-vars.js
tests/lib/rules/no-unused-vars.js

Added code to mark type annotations as used.

Fix: type-annotations are marked as used (fixes #61)

---

lib/rules/no-unused-vars.js
tests/lib/rules/no-unused-vars.js

Added few more test cases and refactored the code

Fix: fixes missing test cases in no-unused-vars (fixes #65)

---

package.json

Updates dependencies: eslint, parser, typescript and others

Chore: Update dependencies

---

lib/rules/adjacent-overload-signatures.js
lib/rules/explicit-member-accessibility.js
lib/rules/member-ordering.js
package.json

Prettier and pin the version

---

tests/lib/rules/adjacent-overload-signatures.js
tests/lib/rules/explicit-member-accessibility.js
tests/lib/rules/interface-name-prefix.js
tests/lib/rules/member-delimiter-style.js
tests/lib/rules/member-naming.js
tests/lib/rules/member-ordering.js
tests/lib/rules/no-angle-bracket-type-assertion.js
tests/lib/rules/no-empty-interface.js
tests/lib/rules/no-explicit-any.js
tests/lib/rules/no-namespace.js
tests/lib/rules/no-parameter-properties.js
tests/lib/rules/no-triple-slash-reference.js
tests/lib/rules/no-type-alias.js
tests/lib/rules/no-unused-vars.js
tests/lib/rules/no-use-before-define.js
tests/lib/rules/prefer-namespace-keyword.js
tests/lib/rules/type-annotation-spacing.js

Reformat the tests to include the parser in the RuleTester instead of per test

Update: refactor tests (fixes #81)

---

lib/rules/adjacent-overload-signatures.js
lib/rules/no-explicit-any.js
lib/rules/no-unused-vars.js
lib/rules/type-annotation-spacing.js
package.json

This will take care of the renamed TS* nodes

Breaking: Support updated ts nodes (fixes #74)

---

docs/rules/member-ordering.md
lib/rules/member-ordering.js
tests/lib/rules/member-ordering.js

Resolves #97 - see discussion in that issue.

Fix: Treat function-type fields as fields, not methods

---

package.json

https://github.com/mysticatea/eslint-plugin-node/releases/tag/v6.0.0

Chore: Update eslint-plugin-node to v6.0.x

---

lib/rules/type-annotation-spacing.js
tests/lib/rules/type-annotation-spacing.js

handle optional annotations in type-annotation-spacing

---

README.md
docs/rules/no-inferrable-types.md
lib/rules/no-inferrable-types.js
tests/lib/rules/no-inferrable-types.js

Related to #5.
Seems all fine, but I only discovered this repo today (and eslint's internals) so do let me know if anything's wrong or could be written better.

add no-inferrable-types rule

---

README.md
docs/rules/generic-type-naming.md
lib/rules/generic-type-naming.js
tests/lib/rules/generic-type-naming.js

https://github.com/nzakas/eslint-plugin-typescript/issues/111

New: Add generic-type-naming (#111)

---

lib/rules/interface-name-prefix.js
tests/lib/rules/interface-name-prefix.js

[FIX] interface-name-prefix failing on interface with number in name

---

lib/rules/type-annotation-spacing.js
package.json
tests/lib/rules/type-annotation-spacing.js

Add support for optional modifiers to type-annotation-spacing.

---

package.json

Forgot about this small detail when I upgraded the dependencies

Fix: husky configuration (fixes #196)

---

lib/rules/no-namespace.js
tests/lib/rules/no-namespace.js

Fix: allow global augmentation in no-namespace

---

.eslintrc
lib/rules/adjacent-overload-signatures.js
lib/rules/class-name-casing.js
lib/rules/explicit-member-accessibility.js
lib/rules/no-inferrable-types.js
lib/rules/type-annotation-spacing.js
package.json
tests/lib/rules/no-angle-bracket-type-assertion.js
tests/lib/rules/type-annotation-spacing.js
yarn.lock

I did set up most common rules from it, but it will be nice if we will have also:
- require-meta-docs-url
- require-meta-type
- report-message-format
see: https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin

chore: Add eslint-plugin-eslint-plugin to warn about potential issues

---

README.md
docs/rules/no-misused-new.md
lib/rules/no-misused-new.js
tests/lib/rules/no-misused-new.js

This PR implements rule [no-misused-new](https://palantir.github.io/tslint/rules/no-misused-new/)
- https://github.com/bradzacher/eslint-plugin-typescript/issues/5

[FEAT] Add rule no-misused-new

---

lib/rules/adjacent-overload-signatures.js
lib/rules/array-type.js
lib/rules/ban-types.js
lib/rules/camelcase.js
lib/rules/class-name-casing.js
lib/rules/explicit-function-return-type.js
lib/rules/explicit-member-accessibility.js
lib/rules/generic-type-naming.js
lib/rules/interface-name-prefix.js
lib/rules/member-delimiter-style.js
lib/rules/member-naming.js
lib/rules/member-ordering.js
lib/rules/no-angle-bracket-type-assertion.js
lib/rules/no-array-constructor.js
lib/rules/no-empty-interface.js
lib/rules/no-explicit-any.js
lib/rules/no-inferrable-types.js
lib/rules/no-namespace.js
lib/rules/no-non-null-assertion.js
lib/rules/no-parameter-properties.js
lib/rules/no-triple-slash-reference.js
lib/rules/no-type-alias.js
lib/rules/no-unused-vars.js
lib/rules/no-use-before-define.js
lib/rules/no-var-requires.js
lib/rules/prefer-namespace-keyword.js
lib/rules/type-annotation-spacing.js
lib/util.js

chore: update all urls and replace them with utils.metaDocsUrl

---

.eslintrc
tests/lib/rules/member-delimiter-style.js
tests/lib/rules/no-object-literal-type-assertion.js
tests/lib/rules/type-annotation-spacing.js

[CHORE] enable eslint rule eslint-plugin/test-case-shorthand-strings

---

README.md

This PR adds shields to [readme ](https://github.com/bradzacher/eslint-plugin-typescript/blob/6dcdf795bc5a192763b0ffc65e6d5a3fc290324d/README.md)
[![NPM version](https://img.shields.io/npm/v/eslint-plugin-typescript.svg)](https://www.npmjs.com/package/eslint-plugin-typescript)  [![NPM downloads](https://img.shields.io/npm/dm/eslint-plugin-typescript.svg)](https://www.npmjs.com/package/eslint-plugin-typescript)  [![TravisCI](https://img.shields.io/travis/bradzacher/eslint-plugin-typescript.svg)](https://travis-ci.com/bradzacher/eslint-plugin-typescript)

[CHORE] Add shields to readme
