README.md, docs/rules/explicit-member-accessibility.md, lib/rules/explicit-member-accessibility.js, package.json, tests/lib/rules/explicit-member-accessibility.js
Rule based off of TSLint's [member-access rule](http://palantir.github.io/tslint/rules/member-access/)
=> New: Add rule explicit-member-accessibility

README.md, docs/rules/no-triple-slash-reference.md, lib/rules/no-triple-slash-reference.js, tests/lib/rules/no-triple-slash-reference.js
Rule based off of TSLint's [no-reference rule](http://palantir.github.io/tslint/rules/no-reference/)
=> New: Add rule no-triple-slash-reference

README.md, docs/rules/no-explicit-any.md, lib/rules/no-explicit-any.js, tests/lib/rules/no-explicit-any.js
Rule based off of TSLint's [no-any](https://palantir.github.io/tslint/rules/no-any/) rule
=> New: Add rule no-any

README.md, docs/rules/interface-name-prefix.md, lib/rules/interface-name-prefix.js, tests/lib/rules/interface-name-prefix.js
Ruled based off of TSLint's [interface-name](https://palantir.github.io/tslint/rules/interface-name/) rule
=> New: Add rule interface-name-prefix

lib/rules/no-angle-bracket-type-assertion.js, tests/lib/rules/no-angle-bracket-type-assertion.js
Modify to no-angle-bracket-type-assertion rule
Add more tests for the rle
=> fix: no-angle-bracket-type-assertion fails with non-reference types (fixes #19)

.eslintrc.yml, .npmrc, docs/rules/type-annotation-spacing.md, lib/index.js, lib/rules/explicit-member-accessibility.js, lib/rules/interface-name-prefix.js, lib/rules/no-angle-bracket-type-assertion.js, lib/rules/no-explicit-any.js, lib/rules/no-namespace.js, lib/rules/no-triple-slash-reference.js, lib/rules/no-unused-vars.js, lib/rules/prefer-namespace-keyword.js, lib/rules/type-annotation-spacing.js, package.json, tests/lib/rules/explicit-member-accessibility.js, tests/lib/rules/interface-name-prefix.js, tests/lib/rules/no-angle-bracket-type-assertion.js, tests/lib/rules/no-explicit-any.js, tests/lib/rules/no-namespace.js, tests/lib/rules/no-triple-slash-reference.js, tests/lib/rules/no-unused-vars.js, tests/lib/rules/prefer-namespace-keyword.js, tests/lib/rules/type-annotation-spacing.js
This should land after #30 I updated the deps. Cleaned up the linting to fit eslint-config-eslint 4 and then fixed the broken tests. I did test against both eslint 3 and 4. We should be ready to add new rules now!
=> Chore: Upgrade deps to eslint 4 and typescript-parser 4

README.md, docs/rules/member-ordering.md, lib/rules/member-ordering.js, tests/lib/rules/member-ordering.js
This includes
New rule member-ordering
=> New: Add rule member-ordering

README.md, docs/rules/no-use-before-define.md, lib/rules/no-use-before-define.js, package.json, tests/.eslintrc.yml, tests/lib/rules/explicit-member-accessibility.js, tests/lib/rules/interface-name-prefix.js, tests/lib/rules/no-angle-bracket-type-assertion.js, tests/lib/rules/no-explicit-any.js, tests/lib/rules/no-namespace.js, tests/lib/rules/no-triple-slash-reference.js, tests/lib/rules/no-type-alias.js, tests/lib/rules/no-unused-vars.js, tests/lib/rules/no-use-before-define.js, tests/lib/rules/prefer-namespace-keyword.js, tests/lib/rules/type-annotation-spacing.js
This adds the `no-use-before-define` rule from core ESLint, with a new `typedefs` option to ignore errors coming from `type` declarations.
=> no-use-before-define

docs/rules/no-explicit-any.md, lib/rules/no-explicit-any.js, tests/lib/rules/no-explicit-any.js
This change improves the existing no-explicit-any rule by adding:
- Check for TSUnionTypes
- Check for TSIntersectionTypes
- Check for TypeReferences (Array<*>) and TSArrayType (any[])
- Check for Arguments in class constructors 
- Check for Properties in classes, interfaces and type aliases
This also adds more tests cases
=> Fix: no-explicit-any Rule does not check generic type (fix #26)

docs/rules/type-annotation-spacing.md, lib/rules/type-annotation-spacing.js, tests/lib/rules/type-annotation-spacing.js
This change improves the existing type-annotation-spacing rule by adding:
- Support for class properties and methods
- Support for interfaces properties and methods
- Add options to control the spacings before and after the colon
=> Fix: type-annotation-spacing rule doesn't work for class properties (fixes #24)

docs/rules/adjacent-overload-signatures.md, lib/rules/adjacent-overload-signatures.js, tests/lib/rules/adjacent-overload-signatures.js
Fixes #49, now export members are handled by recursively calling getMemberName
Also added some missing expressions (TSConstructSignature)
=> Fix: adjacent-overload-signatures fails with type (fixes #49)

docs/rules/type-annotation-spacing.md, lib/rules/type-annotation-spacing.js, tests/lib/rules/type-annotation-spacing.js
Add an override option to the type-annotation-spacing rule
The option allows the developer to override the behavior of type annotations and function types
e.g.
type annotation: const a : number 
function type: type a = (s: string) => string;
=> Update: Add override option to type-annotation-spacing (fixes #41 and #42)

README.md, docs/rules/no-empty-interface.md, lib/rules/no-empty-interface.js, tests/lib/rules/no-empty-interface.js
This includes
New rule no-empty-interface
Related to #5 (TSLint compatibility)
=> New: Add no-empty-interface

README.md, docs/rules/class-name-casing.md, lib/rules/class-name-casing.js, tests/lib/rules/class-name-casing.js
Implements https://github.com/nzakas/eslint-plugin-typescript/issues/5#issuecomment-321985325.
=> New: class-name-casing rule (class-name from TSLint)

README.md, docs/rules/no-parameter-properties.md, lib/rules/no-parameter-properties.js, tests/lib/rules/no-parameter-properties.js
This includes
New rule no-parameter-properties
Related to #5 (TSLint compatibility)
=> New: Add no-parameter-properties

docs/rules/member-delimiter-style.md, lib/rules/member-delimiter-style.js, tests/lib/rules/member-delimiter-style.js
Adds a new option to ignore single line interface and type literal declarations
=> Update: Add ignore single line option to member-delimiter-style (fixes #58)

lib/rules/adjacent-overload-signatures.js, tests/lib/rules/adjacent-overload-signatures.js
Missed a validation that was required to prevent null values to be stored in the seen array
=> Fix: fixes incorrectly marked function call as misplaced (fixes #63)

package.json
This changes the Mocha output to something like this:
```
․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․!․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․ …
```
=> Chore: Use a more-minimal reporter for Mocha

lib/rules/type-annotation-spacing.js, tests/lib/rules/type-annotation-spacing.js
Fixes an issue detected when using typescript-eslint-parser 8.0.0, but the change is backwards compatible with 7.0.0 (tried both). It also fixes an issue in 7.0.0 that will let class/interfaces/types properties go undetected.
=> Fix: fixes an issue with the way type annotations are handled (fixes #69)

README.md, docs/rules/member-naming.md, lib/rules/member-naming.js, tests/lib/rules/member-naming.js
A new rule to enforce naming conventions for class members by visibility.
It can be helpful to enforce naming conventions for `private` (and sometimes `protected`) members of an object. For example, prefixing private properties with a `_` allows them to be easily discerned when being inspected by tools that do not have knowledge of TypeScript (such as most debuggers).
=> New: Add member-naming

docs/rules/no-array-constructor.md, lib/rules/no-array-constructor.js, tests/lib/rules/no-array-constructor.js
Copied from ESLint core, except it allows `new Array<Foo>()` annotations.
=> New: add no-array-constructor rule

lib/rules/no-unused-vars.js, tests/lib/rules/no-unused-vars.js
Includes another case for no-unused-vars. Now Array types are marked as used.
=> Fix: array references marked as used (fixes #77)

lib/rules/no-triple-slash-reference.js, tests/lib/rules/no-triple-slash-reference.js
Trying this rule, I had to fix it by replacing `getComments` with `getCommentsBefore`.
Anyway, [`getComments` seems deprecated](https://eslint.org/docs/developer-guide/working-with-rules#deprecated).
=> Fix no-triple-slash-reference

lib/rules/type-annotation-spacing.js, tests/lib/rules/type-annotation-spacing.js
Handles constructors like.
```ts
interface A {
resolver: (() => PromiseLike<T>) | PromiseLike<T>;
}
```
By excluding punctuators other than `:` and `=>` from the validation
=> Fix: Handles type spacing on TSParenthesizedType expressions (fixes #79)

lib/rules/no-unused-vars.js, tests/lib/rules/no-unused-vars.js
Here is a failing seemingly valid test code.
=> Destructured param type annotation not marked used

lib/rules/no-unused-vars.js, tests/lib/rules/no-unused-vars.js
While type parameters on function declarations/expressions are marked as used, ones on call expressions are not, e.g.:
```ts
import { Foo } from 'foo'
function bar<T>() {}
bar<Foo>() // fails with no-unused-vars
```
=> Fix: Mark call expression type parameters as used

tests/lib/rules/type-annotation-spacing.js
Perhaps there should be more override types to go with `colon` and `arrow`?
This particular example is straight out of no-one's style guide, I assume.
=> failing test: type-annotation-spacing: keyof considered like arrow

lib/rules/class-name-casing.js, tests/lib/rules/class-name-casing.js
When `class-name-casing` is enabled, `class Foo2 {}` will be reported as invalid.
=> Fix class-name-casing cannot recognize PascalCase containing digits

README.md, docs/rules/explicit-function-return-type.md, lib/rules/explicit-function-return-type.js, tests/lib/rules/explicit-function-return-type.js
Adds a new rule that ensures that all function declarations, function expressions, arrow functions, class methods etc. include a type annotation for the return value (including `void` for functions that don't return a value).
The following patterns are considered warnings:
```ts
// Should indicate that no value is returned (void)
function test() {
return;
}
// Should indicate that a number is returned
var fn = function() {
return 1;
}
// Should indicate that a string is returned
var arrowFn = () => 'test';
class Test {
// Should indicate that no value is returned (void)
method() {
return;
}
}
```
The following patterns are not warnings:
```ts
// No return value should be expected (void)
function test(): void {
return;
}
// A return value of type number
var fn = function(): number {
return …
```
=> New: add explicit-function-return-type rule

lib/rules/adjacent-overload-signatures.js, lib/rules/class-name-casing.js, lib/rules/explicit-function-return-type.js, lib/rules/explicit-member-accessibility.js, lib/rules/interface-name-prefix.js, lib/rules/member-delimiter-style.js, lib/rules/member-naming.js, lib/rules/member-ordering.js, lib/rules/no-angle-bracket-type-assertion.js, lib/rules/no-array-constructor.js, lib/rules/no-empty-interface.js, lib/rules/no-explicit-any.js, lib/rules/no-namespace.js, lib/rules/no-parameter-properties.js, lib/rules/no-triple-slash-reference.js, lib/rules/no-type-alias.js, lib/rules/no-unused-vars.js, lib/rules/no-use-before-define.js, lib/rules/prefer-namespace-keyword.js, lib/rules/type-annotation-spacing.js
ESLint v4.15.0 added an official location for rules to store a URL to their documentation in the rule metadata in eslint/eslint#9788. This adds the URL to all the existing rules so anything consuming them can
know where their documentation is without having to resort to external packages to guess.
=> Add URL to rule documentation to the metadata

lib/rules/explicit-function-return-type.js, lib/rules/explicit-member-accessibility.js, lib/util.js, tests/lib/rules/explicit-member-accessibility.js
Modifies the `explicit-member-accessibility` rule by restricting it to only checking *.ts and *.tsx files (Fixes #102).
Note: the proposed new rule `explicit-function-return-type` (#103) has similar functionality (both rules duplicate the `isTypescript(filename)` function.  It may be desirable to move this duplicated function into `utils.js`, so it is available to any rule that needs to limit itself to only operating against Typescript files.
=> Update: explicit-member-accessibility only check *.ts and *.tsx files (Fixes #102)

README.md, docs/rules/no-non-null-assertion.md, lib/rules/no-non-null-assertion.js, tests/lib/rules/no-non-null-assertion.js
This PR adds the [`no-non-null-assertion`](https://palantir.github.io/tslint/rules/no-non-null-assertion/) rule as listed in the description of #5.
Please let me know if there is any wording or formatting that should be adjusted. This is my first time contributing to this codebase, and I tried to match this codebase's conventions. 🙂
=> New: Add no-non-null-assertion

README.md, docs/rules/no-var-requires.md, lib/rules/no-var-requires.js, tests/lib/rules/no-var-requires.js
This PR adds the [`no-var-requires`](https://palantir.github.io/tslint/rules/no-var-requires/) rule as listed in the description of #5.
=> New: Add no-var-requires

package.json
Changes since v1.9.x:
* https://prettier.io/blog/2018/01/10/1.10.0.html
* https://prettier.io/blog/2018/02/26/1.11.0.html
I also ran `npx prettier --tab-width=4 **/*.js --write` after updating, and no files were changed as a result.
=> Chore: Update prettier to v1.11.x

docs/rules/explicit-function-return-type.md, lib/rules/explicit-function-return-type.js, tests/lib/rules/explicit-function-return-type.js
Fixes #123.
Added an option to exclude arrow functions from the explicit return type rule. Seems to be a common exclusion plenty would appreciate.
So code like this can be excluded from the rule:
```ts
arr.filter((item) => item + 1);
```
Personal preference but one could argue it is over the top to require a return type on the above. So figured why not make it a choice.
=> Update: allow expression exclusion from return type checks

lib/rules/adjacent-overload-signatures.js, package.json
This PR updates typescript-eslint-parser and typescript to the latest versions.
The only breaking change in typescript-eslint-parser I could find was in https://github.com/eslint/typescript-eslint-parser/pull/412, which added the `TSEmptyBody` types. Some of the `adjacent-overload-signatures` tests were failing, but adding the `TSEmptyBody` node types to the rule fixed those tests.
If there is something else to be aware of in this update or if there's a better commit message name, please let me know! 😄
=> Chore: Update typescript-eslint-parser and typescript

lib/rules/prefer-namespace-keyword.js, tests/lib/rules/prefer-namespace-keyword.js
Fixes #127.
This PR fixes false positive of `prefer-namespace-keyword` token.
The new logic is more robust because it's token-based instead of text-based. That rule reports `module` keyword to suggest a use of `namespace` keyword, so the new logic finds `module` keyword token. Previously, it reported the declaration if `namespace` keyword was not found, even if `module` keyword was not found.
=> Fix: prefer-namespace-keyword false positive (fixes #127)

lib/rules/no-unused-vars.js, tests/lib/rules/no-unused-vars.js
See #33 
I believe this addresses the first and fourth snippets in https://github.com/nzakas/eslint-plugin-typescript/issues/33#issuecomment-399316751. Any thoughts on other test cases to add or things to consider in this fix?
[Here is a link](http://astexplorer.net/#/gist/2e4055c6371619d206d0f39184c6f835/efbf815025efdfdaa8d6edd3880c8c41b56d1d9a) to an AST Explorer of the test case, if that is helpful for review.
=> Fix: Handle extends generics in no-unused-vars

lib/rules/adjacent-overload-signatures.js, tests/lib/rules/adjacent-overload-signatures.js
=> Fix adjacent-overload-signatures barfing on no-name, generic, default exports

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/feature_request.md
I was running through triaging the existing issues, and I noticed there was a wide variety of formatting and level of information.
This is just an attempt to help make it easier to maintain.
Let me know if you think there is too much / too little / etc in these templates.
=> [DOCS] Create issue templates

lib/rules/no-unused-vars.js, tests/lib/rules/no-unused-vars.js
After updating to the latest, I started seeing this error a lot.
```
TypeError: Cannot read property 'typeAnnotation' of undefined
at markTypeAnnotationAsUsed (/Users/Miles/Sites/boost/node_modules/eslint-plugin-typescript/lib/rules/no-unused-vars.js:71:37)
at markTypeAnnotationAsUsed (/Users/Miles/Sites/boost/node_modules/eslint-plugin-typescript/lib/rules/no-unused-vars.js:126:21)
at Array.forEach (<anonymous>)
at markClassOptionsAsUsed (/Users/Miles/Sites/boost/node_modules/eslint-plugin-typescript/lib/rules/no-unused-vars.js:260:44)
at listeners.(anonymous function).forEach.listener (/Users/Miles/Sites/boost/node_modules/eslint/lib/util/safe-emitter.js:45:58)
at Array.forEach (<anonymous>)
at Object.emit (/Users/Miles/Sites/boost/node_modules/eslint/lib/util/safe-emitter.js:45:38)
at …
```
=> Fix type param constraint. Support defaults.

lib/rules/no-unused-vars.js, tests/lib/rules/no-unused-vars.js
Fixes false positives demonstrated in these test cases (type parameter in new expression, type parameter constraints):
```javascript
import { Nullable } from 'nullable';
class A<T> {
bar: T
}
new A<Nullable>();
```
```javascript
import { Nullable } from 'nullable';
import { SomeOther } from 'other';
function foo<T extends Nullable>() {
}
foo<SomeOther>();
```
```javascript
import { Nullable } from 'nullable';
import { SomeOther } from 'other';
class A<T extends Nullable> {
bar: T;
}
new A<SomeOther>();
```
```javascript
import { Nullable } from 'nullable';
import { SomeOther } from 'other';
interface A<T extends Nullable> {
bar: T;
}
const a: A<SomeOther> = {
foo: "bar"
};
console.log(a);
```
=> [FIX] [no-unused-vars] address more false positives

.gitignore, lib/rules/no-type-alias.js, package.json, tests/lib/rules/explicit-member-accessibility.js, tests/lib/rules/member-ordering.js, tests/lib/rules/no-type-alias.js
typescript 2.9
typescript-eslint-parser: 17.0.1
solve #137
=> Upgrade typescript-eslint-parser to 17.0.1

.github/no-response.yml
as suggested by @j-f1 on #112 
I've already added the bot to the repo, this is just configuring the wait period and required label
=> [CHORE] Configure no-response bot

lib/rules/no-unused-vars.js, package.json, tests/lib/rules/no-unused-vars.js
Fixes #150 
Whilst `TSParameterProperty`s are arguments, they are also technically class properties.
`no-unused-vars` has no handling for class properties, so just mark them as used.
=> [FIX][no-unused-vars] assume constructor parameter args are used

lib/rules/no-use-before-define.js, tests/lib/rules/no-use-before-define.js
Fixes #142
The problem was it was failing to accept the case when both the def and the var were in the top-level global/module scope
=> [FIX] [no-use-before-define] fix top level scope handling

package.json
Again... lots of lines due to style formatting.
Real change is:
```json
"lint-staged": {
"*.js": [
"yarn format",
"git add"
]
}
```
=> Fix: lint-staged script (fixes #190)

.gitignore, README.md, lib/rules/class-name-casing.js, lib/rules/member-delimiter-style.js, lib/rules/no-type-alias.js, package.json, parser.js, yarn.lock
Updates package dependencies and introduces eslint and typescript-eslint-parser as peer dependencies
Considerations:
1. The PR includes minor lint changes to 3 rules introduced with the newer eslint version
2. The PR bumps all versions to latest except: eslint-plugin-node (peer dependency of eslint-config-eslint), typescript and typescript-eslint-parser (these two being worked in #174)
3. Peer dependencies are kind of loose (at least eslint), we can change that...
=> chore: update package dependencies (fixes #184)

README.md
This package now depends directly on typescript-eslint-parser, so no need to do that.
=> Remove extra step in readme.md

.editorconfig, .gitignore, .travis.yml, .vscode/extensions.json, .vscode/settings.json, CONTRIBUTING.md, README.md, package.json
The vscode autoformatter is completely at odds with prettier, so if you don't have the prettier extension installed, you end up with wild changes.
Additionally if you've got both the beautify and prettier extensions installed, it can cause some serious issues.
Forcing it to be on will probably cause a lot of headaches to anyone trying to contribute unless they get their environment setup perfectly (sorry @weirdpattern for earlier!!)
=> [DOCS] Add contributing to README, and disable vscode autoformat

lib/rules/class-name-casing.js, tests/lib/rules/class-name-casing.js
This PR adds support for TSAbstractClassDeclaration in `class-name-casing` and fixes issue with:
```ts
var ba_zz = class Foo {};
```
ba_zz was reported as not PascalCase even if class name is Foo
=> Fix class-name-casing for TSAbstractClassDeclaration

lib/rules/prefer-namespace-keyword.js, tests/lib/rules/prefer-namespace-keyword.js
This PR fixes issue #188
modules can have no body.
-----
there was so much weird logic with tokens there, and we don't need it, it should just take `id` and previous token (module/namespace)....
=> Fix issue with declare module without body in prefer-namespace-keyword

.npmignore
In current configuration of `.npmignore` there is ignored `parser.js` file so `parser: 'eslint-plugin-typescript/parser',` not working because is missing in package on npm registry.
=> add missing parser.js to npmignore

lib/rules/no-explicit-any.js, lib/rules/no-unused-vars.js, lib/rules/type-annotation-spacing.js, package.json, tests/lib/rules/indent.js, tests/lib/rules/no-explicit-any.js, tests/lib/rules/no-undef.js, tests/lib/rules/no-unused-vars.js, tests/lib/rules/type-annotation-spacing.js, yarn.lock
To make it work this PR has to be merged due to bug in visitor-tree
unblocks #117, #181 PR
fixes: #152, #155, #126, #164, #166, #171, #193, #189, #143, #33
=> Migrate typescript-eslint-parser to 21.0.2

README.md, docs/rules/ban-types.md, lib/rules/ban-types.js, tests/lib/rules/ban-types.js
I ported this rule and tests from tslint, additionally i added some extra tests to check more cases
this rule relies on changes from https://github.com/bradzacher/eslint-plugin-typescript/pull/174
=> Add `ban-types` rule

docs/rules/member-delimiter-style.md, lib/rules/member-delimiter-style.js, tests/lib/rules/member-delimiter-style.js
This PR adds better handling for single line delimiters, and better enforces the `requrieLast` option.
Fixes #92
Previously single line delimiters were either checked or not. This meant that if you used
```
{
delimiter: "none",
ignoreSingleLine: false,
}
```
then the fixer would break your code by removing the delimiter from single line statements i.e.:
```TS
interface Foo { bar: string, baz: number }
// fixed to this broken line
interface Foo { bar: string baz: number }
```
- Removed option `ignoreSingleLine`
- Added option `singleLine: "none" | "semi" | "comma"`
`singleLine` works the same as `delimiter`, except for single line statements only.
Previously `requireLast` did nothing when turned off, and enforced having a delimiter when turned on.
I felt this was inconsistent with the …
=> [FEAT][BREAKING][1/2][member-delimiter-style] Better handling for single line

docs/rules/member-delimiter-style.md, lib/rules/member-delimiter-style.js, lib/util.js, tests/lib/rules/member-delimiter-style.js
Changed config to split single and multiline config into two separate objects for better customisability
Before:
```ts
type Delimiter = 'none' | 'semi' | 'comma';
interface BaseConfig {
delimiter ?: Delimiter
requireLast ?: boolean
singleLine ?: Delimiter
}
type Config = BaseConfig & {
overrides ?: {
interface ?: BaseConfig
typeLiteral ?: BaseConfig
}
}
```
After:
```ts
type Delimiter = 'none' | 'semi' | 'comma';
interface BaseConfig {
multiline ?: {
delimiter ?: 'none' | 'semi' | 'comma'
requireLast ?: boolean
}
singleline ?: {
delimiter ?: 'semi' | 'comma'
requireLast ?: boolean
}
}
type Config = BaseConfig & {
overrides ?: {
interface ?: BaseConfig
typeLiteral ?: BaseConfig
}
}
```
=> [FEAT][BREAKING][2/2][member-delimiter-style] Separate single/multiline config

package.json
https://yarnpkg.com/lang/en/docs/cli/check/#toc-yarn-check-verify-tree
`yarn check` will ensure that your dependencies are up-to-date before committing.
This ensures that when you raise a PR, travis will not fail due to an error introduced in a new version of a tool.
=> [CHORE] Add yarn check to precommit

.editorconfig, README.md, docs/rules/array-type.md, lib/rules/array-type.js, tests/.eslintrc.yml, tests/lib/rules/array-type.js
=> Add rule array-type

README.md, docs/rules/no-object-literal-type-assertion.md, lib/rules/no-object-literal-type-assertion.js, tests/lib/rules/no-object-literal-type-assertion.js
This PR implements rule [no-object-literal-type-assertion](https://palantir.github.io/tslint/rules/no-object-literal-type-assertion/)
- #5
=> [FEAT] Add rule no-object-literal-type-assertion

lib/rules/no-triple-slash-reference.js, tests/lib/rules/no-triple-slash-reference.js
but it's triggered on:
- `/// <reference types="foo" />`
- `/// <reference lib="es2017.string" />`
- `/// <reference no-default-lib="true"/>`
types/lib/no-default-lib can't be replaced by es6 imports
=> Fix false positives in no-triple-slash-reference

lib/rules/no-unused-vars.js, tests/lib/rules/no-unused-vars.js
=> [FIX][no-unused-vars] add EnumMember

.gitattributes
When user has `git core.autocrlf` set to crlf on windows machines there are collisions between `eslint-docs` and `prettier` due to inconsistent line endings in md files.
fixes: #249
@uniqueiniquity
=> [CHORE] Fix issue with line ending chars in .gitattributes

lib/rules/no-namespace.js, lib/util.js, tests/lib/rules/no-namespace.js, tests/lib/util.js
This PR changes logic in no-namespace rule and fixing some annoying bugs
- improve definition file detection
- migrate messages to messageId
- correct reporting `namespace Foo.Bar {}`
- add unit tests for isDefinitionFile & isTypescript
- add tests for allowDefinitionFiles
=> [FIX] Refactor no-namespace rule

docs/rules/no-type-alias.md, lib/rules/no-type-alias.js, lib/util.js, tests/lib/rules/no-type-alias.js
In standardising our config, we should *either* use booleans, or strings.
Offering the ability to configure the rule via `true`/`false` as well as `"always"`/`"never"` makes the docs harder to understand.
- [breaking] remove true/false options
- cleanup tests/docs
- switch to messageId
=> [BREAKING] [no-type-alias] simplify config

README.md, docs/rules/indent.md, docs/rules/no-unused-vars.md, lib/configs/recommended.json, lib/rules/no-unused-vars.js, tests/lib/rules/no-unused-vars.js
Similar to what we've done with both indent, and camelcase.
Rather than forcing users to configure both our rule and the base rule (which has been a source of confusion), this lets users just use our rule.
```diff
{
-    "no-unused-vars": ["error", { config }],
+    "no-unused-vars": "off",
-    "typescript/no-unused-vars": "error",
+    "typescript/no-unused-vars": ["error", { config }],
}
```
=> [FEAT] [BREAKING] [no-unused-vars] remove implicit dep on base rule

.gitignore, .prettierignore, package.json, yarn.lock
| File                                  |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
|---------------------------------------|----------|----------|----------|----------|-------------------|
| All files                             |    97.23 |    92.88 |    98.85 |    97.46 |                   |
|  lib                                  |      100 |    92.86 |      100 |      100 |                   |
|   util.js                             |      100 |    92.86 |      100 |      100 |                26 |
|  lib/rules                            |    97.15 |    92.88 |    98.82 |     97.4 |                   |
|   adjacent-overload-signatures.js     |    95.83 |    84.21 |      100 |      100 |       40,42,60,88 |
|   array-type.js                       |    96.43 | …
=> [TEST] Add coverage report after running tests

lib/util.js
@armano2 closed #245 because it won't be needed.
But it had a helpful function in it for us to ensure people are using our parser, so we don't get cryptic error messages about reading properties from undefined.
=> [FEAT] Add getParserServices function

lib/rules/indent.js, tests/lib/rules/indent.js
-   [X] I’ve added tests for my changes
Fixes #271
=> [FIX] [indent] add handling for TSTypeReference
